# library(arrow)
rm(list = ls())
library(dplyr)
library(fixest)
library(ggplot2)
library(parallel)
library(DescTools)
# library(reshape2)
library(tictoc)
library(haven)
library(rstudioapi)
options(scipen = 10)
library(showtext)
library(sandwich)
library(styler)
showtext_auto()
library(data.table)
nc <- detectCores() - 2
